# Create docker service for ElasticSearch and kibana
version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.17.4
    container_name: elasticsearch
    restart: always
    environment:
      # - xpack.security.enabled=true
      - discovery.type=single-node
    ulimits:
      memlock: 
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticserach-data-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.6.1
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  elasticserach-data-volume:
    driver: local

